In [1]:
import pandas as pd
import numpy as np

In [30]:
df = pd.read_csv('C:/Users/MR.AMAN SAINI/Downloads/smartwatches.csv')

In [33]:
del(df['Unnamed: 0'])

In [34]:
df.columns

Index(['Brand', 'Current Price', 'Original Price', 'Discount Percentage',
       'Rating', 'Number OF Ratings', 'Model Name', 'Dial Shape',
       'Strap Color', 'Strap Material', 'Touchscreen', 'Battery Life (Days)',
       'Bluetooth', 'Display Size', 'Weight'],
      dtype='object')

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Brand                450 non-null    object
 1   Current Price        440 non-null    float64
 2   Original Price       377 non-null    float64
 3   Discount Percentage  377 non-null    float64
 4   Rating               444 non-null    float64
 5   Number OF Ratings    391 non-null    float64
 6   Model Name           415 non-null    object
 7   Dial Shape           327 non-null    object
 8   Strap Color          327 non-null    object
 9   Strap Material       381 non-null    object
 10  Touchscreen          413 non-null    object
 11  Battery Life (Days)  418 non-null    float64
 12  Bluetooth            444 non-null    object
 13  Display Size         420 non-null    object
 14  Weight               264 non-null    object
dtypes: float64(6), object(9)
memory usage: 52.9+ KB

In [36]:
df.describe()

,Current Price,Original Price,Discount Percentage,Rating,Number OF Ratings,Battery Life (Days)
count,440.000000,377.000000,377.000000,444.000000,391.000000,418.000000
mean,12747.554545,14598.204244,48.236894,4.031306,11594.726343,14.077392
std,17760.666099,15450.028869,24.109830,0.550548,40423.889227,7.718503
min,1199.000000,1669.000000,-79.688436,1.000000,1.000000,0.750000
25%,2180.750000,5999.000000,33.337037,3.900000,68.500000,8.000000
50%,3999.000000,7999.000000,54.550414,4.100000,996.000000,17.500000
75%,17121.750000,17999.000000,66.677780,4.300000,6022.000000,22.000000
max,139990.000000,96390.000000,91.004550,5.000000,619130.000000,22.000000

In [37]:
df.dtypes[df.dtypes=='object']

Brand             object
Model Name        object
Dial Shape        object
Strap Color       object
Strap Material    object
Touchscreen       object
Bluetooth         object
Display Size      object
Weight            object
dtype: object

In [38]:
df['Brand'].value_counts()

fire-boltt    60
noise         43
garmin        41
zebronics     33
pebble        33
boat          32
samsung       30
apple         26
dizo          25
fossil        24
gizmore       23
fitbit        21
huawei        15
honor         14
amazfit       14
ambrane       11
crossbeats     4
hammer         1
Name: Brand, dtype: int64

In [62]:
df1 = pd.DataFrame(df)

In [64]:
type(df1)

pandas.core.frame.DataFrame

In [88]:
top = pd.DataFrame(df1.groupby("Brand")["Model Name"].count())
top["Avg"] = df1.groupby("Brand")["Rating"].mean()
top["total"] = df1.groupby("Brand")["Number OF Ratings"].sum()
top.columns = ["Total Models", "Average Ratings", "Total Reviews"]
top.sort_values("Total Reviews", ascending=False).head()

            Total Models  Average Ratings  Total Reviews
Brand
noise                 41         4.069767      1592535.0
boat                  27         3.996774      1414885.0
fire-boltt            60         3.475439       490099.0
dizo                  19         3.876000       346145.0
apple                 26         4.553846       172184.0

In [119]:
df[df['Weight']=='20 - 35 g']

,Brand,Current Price,Original Price,Discount Percentage,Rating,Number OF Ratings,Model Name,Dial Shape,Strap Color,Strap Material,Touchscreen,Battery Life (Days),Bluetooth,Display Size,Weight
15,noise,1499.0,4999.0,70.014003,4.0,93075.0,wrb-sw-colorfitpro2-std-blk,NaN,NaN,Polycarbonate,Yes,3.6,Yes,1.3 inches,20 - 35 g
43,crossbeats,2999.0,9999.0,70.007001,4.3,674.0,Grit,NaN,NaN,NaN,Yes,12.5,Yes,1.8 inches,20 - 35 g
45,crossbeats,5999.0,14999.0,60.004000,4.3,996.0,Infinti 2.0,NaN,NaN,NaN,Yes,8.0,Yes,1.4 inches,20 - 35 g
49,samsung,NaN,NaN,NaN,4.3,5228.0,NaN,NaN,NaN,NaN,NaN,3.6,Yes,4.4 inches,20 - 35 g
50,samsung,17999.0,19990.0,9.959980,4.3,5228.0,NaN,NaN,NaN,NaN,NaN,3.6,Yes,4.4 inches,20 - 35 g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380,pebble,3069.0,4999.0,38.607722,4.0,1371.0,Pace Unisex Smart Watch with Full Touch Dynami...,Rectangle,Black,Silicon,Yes,22.0,Yes,1.4 inches,20 - 35 g
387,pebble,2999.0,4999.0,40.008002,4.0,1371.0,Pace Unisex Smart Watch with Full Touch Dynami...,Rectangle,Blue,Silicon,Yes,22.0,Yes,1.4 inches,20 - 35 g
390,zebronics,2199.0,4999.0,56.011202,3.9,272.0,Zeb-Fit Me,Square,Green,Thermo Plastic Polyurethene,Yes,22.0,Yes,3.3 inches,20 - 35 g
401,zebronics,1799.0,3999.0,55.013753,4.2,1823.0,ZEB-FIT8220CH,Square,Rose Gold,Silicon,Yes,22.0,Yes,4.3 inches,20 - 35 g
403,zebronics,1399.0,4499.0,68.904201,4.0,469.0,ZEB-FIT920CH,Square,Red,Thermo Plastic Polyurethene,Yes,22.0,Yes,3.5 inches,20 - 35 g

In [109]:

top = pd.DataFrame(df1.groupby("Brand")['Model Name'].count())
top["Avg"] = df1.groupby("Brand")["Current Price"].mean()
top["total"] = df1.groupby("Brand")["Weight"].count()
top.columns = ["Total Models", "Average Ratings", "Total Reviews"]
top.sort_values("Total Reviews", ascending=False).head()

            Total Models  Average Ratings  Total Reviews
Brand
samsung               25     25312.068966             30
noise                 41      4029.023256             26
apple                 26     43161.307692             24
dizo                  19      3010.708333             24
fire-boltt            60      3280.389831             22

In [121]:
df['Dial Shape'].value_counts()

Circle          131
Square          101
Rectangle        87
Curved            6
Contemporary      1
Oval              1
Name: Dial Shape, dtype: int64

In [124]:
df['Number OF Ratings'].sum()

4533538.0

In [123]:
df

,Brand,Current Price,Original Price,Discount Percentage,Rating,Number OF Ratings,Model Name,Dial Shape,Strap Color,Strap Material,Touchscreen,Battery Life (Days),Bluetooth,Display Size,Weight
0,noise,82990.0,89900.0,7.686318,4.0,65.0,Wrb-sw-colorfitpro4alpha-std-rgld_pnk,NaN,NaN,NaN,NaN,8.0,Yes,NaN,35 - 50 g
1,fire-boltt,3799.0,16999.0,77.651627,4.3,20788.0,BSW046,NaN,NaN,Silicon,Yes,3.5,Yes,1.8 inches,50 - 75 g
2,boat,1999.0,7990.0,74.981227,3.8,21724.0,Wave Call,NaN,NaN,Silicon,Yes,8.0,Yes,1.7 inches,35 - 50 g
3,fire-boltt,1799.0,19999.0,91.004550,4.3,13244.0,BSW053,NaN,NaN,Silicon,Yes,3.5,Yes,1.8 inches,75g +
4,noise,1599.0,4999.0,68.013603,4.1,13901.0,Wrb-sw-colorfitpulsegobuzz-std-blk_blk,NaN,NaN,Other,Yes,8.0,Yes,1.7 inches,35 - 50 g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445,fire-boltt,5999.0,8999.0,33.337037,2.5,NaN,bsw003,Circle,Grey,Silicon,Yes,22.0,Yes,1.3 inches,NaN
446,fire-boltt,3700.0,9999.0,62.996300,NaN,NaN,beast pro,Square,Black,Silicon,Yes,8.0,Yes,0.1 inches,NaN
447,fire-boltt,5999.0,8999.0,33.337037,2.5,NaN,bsw003,Circle,Gold,Silicon,Yes,22.0,Yes,1.3 inches,NaN
448,fire-boltt,3200.0,7999.0,59.994999,NaN,NaN,call 2,Square,Blue,Silicon,Yes,22.0,Yes,0.1 inches,NaN
449,fire-boltt,3000.0,7999.0,62.495312,NaN,NaN,call 2,Square,Black,Silicon,Yes,22.0,Yes,0.1 inches,NaN